=== denodoro/org.openscada.orilla/org.openscada.da.client.viewer/schema/Viewer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://openscada.org/DA/Viewer"
	xmlns:viewer="http://openscada.org/DA/Viewer"
	xmlns:common="http://openscada.org/Common"
	>

 <import namespace="http://openscada.org/Common" schemaLocation="openscada_da_server_common/Common.xsd"/>



	<element name="root" type="viewer:RootType"></element>
	
    <complexType name="RootType">
    	<sequence>
    		<element name="factories" type="viewer:FactoriesType" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="views" type="viewer:ViewsType" maxOccurs="1"
    			minOccurs="1">
    		</element>
    	</sequence></complexType>

    <complexType name="FactoriesType">
    	<sequence>
    		<element name="container-factory" type="viewer:ContainerFactoryType"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="object-factory" type="viewer:ObjectFactoryType"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="connector-factory" type="viewer:ConnectorFactoryType"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    	</sequence></complexType>

    <complexType name="ViewsType">
    	<sequence>
    		<element name="view" type="viewer:ViewType" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence></complexType>

	<complexType name="BaseFactoryType">
    	<sequence>
    		<any processContents="lax" maxOccurs="1" minOccurs="0"></any>
    	</sequence>
    	<attribute name="id" type="string" use="required"></attribute>
    	<attribute name="class" type="common:ClassType" use="required"></attribute>

	</complexType>

    <complexType name="ObjectFactoryType">
    	<complexContent>
    		<extension base="viewer:BaseFactoryType"></extension>
    	</complexContent>
    </complexType>

    <complexType name="ConnectorFactoryType">
    	<complexContent>
    		<extension base="viewer:BaseFactoryType"></extension>
    	</complexContent>
    </complexType>

    <complexType name="ViewType">
    	<complexContent>
    		<extension base="viewer:ContainerType">
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="ObjectsType">
    	<choice maxOccurs="unbounded" minOccurs="0">
    		<element name="constant" type="viewer:ConstantType"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="object" type="viewer:ObjectType"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="template-object" type="viewer:TemplateObjectType"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="container" type="viewer:ContainerType"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    	</choice></complexType>

    <complexType name="ConnectorsType">
    	<sequence>
    		<element name="connector" type="viewer:ConnectorType"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    	</sequence></complexType>

    <complexType name="ConnectorType">
    	<sequence>
    		<element name="output" type="viewer:OutputType" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="input" type="viewer:InputType" maxOccurs="1"
    			minOccurs="1">
    		</element>
    	</sequence>
    	<attribute name="type" type="string"></attribute>
    </complexType>

    <complexType name="ConstantType">
    	<choice maxOccurs="1" minOccurs="1">
    		<element name="variant" type="common:VariantType">
    		</element>
    		<element name="integer" type="viewer:ValueIntegerType"></element>
    		<element name="boolean" type="viewer:ValueBooleanType"></element>
    		<element name="null" type="viewer:ValueNullType">
    		</element>
    		<element name="double" type="viewer:ValueDoubleType"></element>
    		<element name="string" type="string"></element>
    		<element name="color" type="viewer:ColorType"></element>
    	</choice>
    	<attribute name="id" type="string" use="required"></attribute>    	
    </complexType>
    
    <complexType name="ColorType">
    	<attribute name="red" use="required" type="int"></attribute>
    	<attribute name="green" use="required" type="int"></attribute>
    	<attribute name="blue" use="required" type="int"></attribute>
    </complexType>
    
    <complexType name="ObjectType">
        <sequence>
        	<element name="property" type="viewer:PropertyType" maxOccurs="unbounded" minOccurs="0"></element>
        </sequence>
        <attribute name="id" type="string" use="required"></attribute>
    	<attribute name="type" type="string" use="required"></attribute>
    </complexType>

    <complexType name="TemplateObjectType">
        <sequence>
        	<element name="property" type="viewer:PropertyType" maxOccurs="unbounded" minOccurs="0"></element>
        </sequence>
    	<attribute name="id" type="string" use="required"></attribute>
    	<attribute name="template" type="string" use="required"></attribute>
    </complexType>

    <complexType name="ValueNullType"></complexType>

    <complexType name="PropertyType">
    	<simpleContent>
    		<extension base="string">
    			<attribute name="name" type="QName"></attribute>
    		</extension>
    	</simpleContent>
    </complexType>

    <complexType name="InputType">
    	<attribute name="object" type="string" use="required"></attribute>
    	<attribute name="name" type="string" use="required"></attribute>
    </complexType>

    <complexType name="OutputType">
    	<attribute name="object" type="string" use="required"></attribute>
    	<attribute name="name" type="string" use="required"></attribute>
    </complexType>

    <complexType name="ValueIntegerType">
    	<simpleContent>
    		<extension base="long"></extension>
    	</simpleContent>
    </complexType>

    <complexType name="ValueBooleanType">
    	<simpleContent>
    		<extension base="boolean"></extension>
    	</simpleContent>
    </complexType>

    <complexType name="ValueDoubleType">
    	<simpleContent>
    		<extension base="double"></extension>
    	</simpleContent>
    </complexType>

    <complexType name="ContainerType">
    
        <sequence>
        	<element name="property" type="viewer:PropertyType"
        		maxOccurs="unbounded" minOccurs="0">
        	</element>
        	<element name="objects" type="viewer:ObjectsType" maxOccurs="1"
        		minOccurs="0">
        	</element>
        	<element name="connectors" type="viewer:ConnectorsType"
        		maxOccurs="1" minOccurs="0">
        	</element>
			<element name="outputs" type="viewer:OutputsType"
				maxOccurs="1" minOccurs="0">
			</element>
			<element name="inputs" type="viewer:InputsType"
				maxOccurs="1" minOccurs="0">
			</element>
        </sequence>
        <attribute name="type" type="string" use="required"></attribute>
        <attribute name="id" type="string" use="required"></attribute>
    </complexType>

    <complexType name="ContainerFactoryType">
    	<complexContent>
    		<extension base="viewer:BaseFactoryType"></extension>
    	</complexContent>
    </complexType>
    
        
    <complexType name="OutputsType">
    	<sequence>
    		<element name="output-export" type="viewer:OutputExportType"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    	</sequence></complexType>

    <complexType name="InputsType">
    	<sequence>
    		<element name="input-export" type="viewer:InputExportType"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    	</sequence></complexType>

    <complexType name="OutputExportType">
    	<complexContent>
    		<extension base="viewer:ExportType">
    			<sequence></sequence>
    		</extension>
    	</complexContent>
    </complexType>
    
    <complexType name="InputExportType">
    	<complexContent>
    		<extension base="viewer:ExportType">
    			<sequence></sequence>
    		</extension>
    	</complexContent>
    </complexType>
    
    <complexType name="ExportType">
    	<attribute name="name" type="string" use="required"></attribute>
    	<attribute name="object" type="string"  use="required"></attribute>
    	<attribute name="export-name" type="string"  use="required"></attribute>
    </complexType>
    
</schema>

=== denodoro/org.openscada.orilla/org.openscada.da.client.viewer/view.xml
<?xml version="1.0" encoding="UTF-8"?>

<viewer:root
  xmlns:common="http://openscada.org/Common"
  xmlns:viewer="http://openscada.org/DA/Viewer"
  xmlns:template="http://openscada.org/DA/Viewer/Template"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://openscada.org/DA/Viewer schema/Viewer.xsd http://openscada.org/Common http://schema.openscada.org/Common.xsd http://openscada.org/DA/Viewer/Template schema/TemplateObject.xsd"
  >
  
	<factories>
		<container-factory id="figure" class="org.openscada.da.client.viewer.model.impl.containers.FigureContainerFactory"/>
		<container-factory id="view" class="org.openscada.da.client.viewer.model.impl.containers.BasicViewFactory"/>
		<container-factory id="hidden" class="org.openscada.da.client.viewer.model.impl.containers.HiddenContainerFactory"/>
		<container-factory id="command" class="org.openscada.da.client.viewer.model.impl.containers.CommandContainer"/>
		<container-factory id="entryCommand" class="org.openscada.da.client.viewer.model.impl.containers.EntryCommandContainer"/>
		
		<object-factory id="line" class="org.openscada.da.client.viewer.model.impl.figures.Line"/>
		<object-factory id="polyline" class="org.openscada.da.client.viewer.model.impl.figures.Polyline"/>
		<object-factory id="label" class="org.openscada.da.client.viewer.model.impl.figures.Label"/>
		<object-factory id="rectangle" class="org.openscada.da.client.viewer.model.impl.figures.Rectangle"/>
		<object-factory id="ellipse" class="org.openscada.da.client.viewer.model.impl.figures.Ellipse"/>
		<object-factory id="triangle" class="org.openscada.da.client.viewer.model.impl.figures.Triangle"/>
		<object-factory id="item" class="org.openscada.da.client.viewer.model.impl.items.DataItemObject"/>
		<object-factory id="viewLink" class="org.openscada.da.client.viewer.model.impl.figures.ViewLink"/>
		<object-factory id="commandButton" class="org.openscada.da.client.viewer.model.impl.figures.CommandButton"/>
		
		<object-factory id="percentBar" class="org.openscada.da.client.viewer.model.impl.widgets.PercentBar"/>
		
		<object-factory id="colorcomposer" class="org.openscada.da.client.viewer.model.impl.converter.ColorComposer"/>
		<object-factory id="modulo" class="org.openscada.da.client.viewer.model.impl.converter.ModuloCalculator"/>
		<object-factory id="factor" class="org.openscada.da.client.viewer.model.impl.converter.FactorCalculator"/>
		
		<object-factory id="variantasboolean" class="org.openscada.da.client.viewer.model.impl.converter.VariantBooleanConverter"/>
		<object-factory id="variantasinteger" class="org.openscada.da.client.viewer.configurator.xml.XMLObjectFactory">
			<arg class="org.openscada.da.client.viewer.model.impl.converter.SimpleVariantIntegerConverter"/>
		</object-factory>
		<object-factory id="variantasdouble" class="org.openscada.da.client.viewer.configurator.xml.XMLObjectFactory">
			<arg class="org.openscada.da.client.viewer.model.impl.converter.SimpleVariantDoubleConverter"/>
		</object-factory>
		<object-factory id="d2i" class="org.openscada.da.client.viewer.configurator.xml.XMLObjectFactory">
			<arg class="org.openscada.da.client.viewer.model.impl.converter.Double2IntegerConverter"/>
		</object-factory>
		
		<object-factory id="if" class="org.openscada.da.client.viewer.model.impl.converter.If"/>
		<object-factory id="boolean2matrix" class="org.openscada.da.client.viewer.model.impl.converter.Boolean2Matrix"/>

		<object-factory id="mov-cmd" class="org.openscada.da.client.viewer.configurator.xml.XMLTemplateFactory">
			<template:template id="mov-cmd" type="figure">
				<objects>					
					<container type="command" id="c1">
						<property name="commands">open-command|Open,close-command|Close</property>
		
						<objects>
							<template-object template="mov" id="mov1"/>
						</objects>
						
						<connectors>
						</connectors>
						
						<inputs>
							<input-export object="mov1" name="open-signal" export-name="open-signal"/>
							<input-export object="mov1" name="close-signal" export-name="close-signal"/>
						</inputs>
						
					</container>
				</objects>

				<connectors>
				</connectors>

				<outputs>
					<output-export object="c1" name="open-command" export-name="open-command"/>
					<output-export object="c1" name="close-command" export-name="close-command"/>
				</outputs>

				<inputs>
					<input-export object="c1" name="open-signal" export-name="open-signal"/>
					<input-export object="c1" name="close-signal" export-name="close-signal"/>
				</inputs>
				
			</template:template>
		</object-factory>
				
		<object-factory id="mov" class="org.openscada.da.client.viewer.configurator.xml.XMLTemplateFactory">
			<template:template id="mov" type="figure">

				<objects>
					<constant id="mov_fatal"><color red="255" green="0" blue="255"/></constant>
					<constant id="mov_opened"><color red="0" green="255" blue="0"/></constant>
					<constant id="mov_transit"><color red="255" green="255" blue="0"/></constant>
					<constant id="mov_closed"><null/></constant>
					<constant id="mov_error"><color red="255" green="0" blue="0"/></constant>
					
					<object type="rectangle" id="rect1">
						<property name="x">0</property>
						<property name="y">0</property>
						<property name="width">24</property>
						<property name="height">24</property>
					</object>
					<object type="triangle" id="tri1">
						<property name="x">2</property>
						<property name="y">2</property>
						<property name="width">10</property>
						<property name="height">20</property>
						<property name="direction">2</property>
					</object>
					<object type="triangle" id="tri2">
						<property name="x">12</property>
						<property name="y">2</property>
						<property name="width">10</property>
						<property name="height">20</property>
						<property name="direction">8</property>
					</object>
					<object type="boolean2matrix" id="oc_matrix_1"/>
					<object type="variantasboolean" id="v2b_opened"/>
					<object type="variantasboolean" id="v2b_closed"/>

				</objects>
				<connectors>
					<connector type="default">
						<output object="mov_fatal" name="value"/>
						<input object="oc_matrix_1" name="defaultValue"/>
					</connector>
					<connector type="default">
						<output object="mov_transit" name="value"/>
						<input object="oc_matrix_1" name="value00"/>
					</connector>
					<connector type="default">
						<output object="mov_opened" name="value"/>
						<input object="oc_matrix_1" name="value01"/>
					</connector>
					<connector type="default">
						<output object="mov_closed" name="value"/>
						<input object="oc_matrix_1" name="value10"/>
					</connector>
					<connector type="default">
						<output object="mov_error" name="value"/>
						<input object="oc_matrix_1" name="value11"/>
					</connector>
					<connector type="default">
						<output object="oc_matrix_1" name="value"/>
						<input object="tri1" name="backgroundColor"/>
					</connector>
					<connector type="default">
						<output object="oc_matrix_1" name="value"/>
						<input object="tri2" name="backgroundColor"/>
					</connector>
					
					<connector type="default">
						<output object="v2b_opened" name="value"/>
						<input object="oc_matrix_1" name="valueA"/>
					</connector>
					<connector type="default">
						<output object="v2b_closed" name="value"/>
						<input object="oc_matrix_1" name="valueB"/>
					</connector>
					
				</connectors>
				<outputs>
				</outputs>
				
				<inputs>
					<input-export object="v2b_opened" name="value" export-name="open-signal"/>
					<input-export object="v2b_closed" name="value" export-name="close-signal"/>
				</inputs>
				
			</template:template>
		</object-factory>
		
		<object-factory id="variant_cc" class="org.openscada.da.client.viewer.configurator.xml.XMLTemplateFactory">
			<template:template id="variant_cc" type="hidden">
				<objects>
					<object type="colorcomposer" id="cc">
						<property name="red">0</property>
						<property name="green">0</property>
						<property name="blue">0</property>
					</object>
					<object type="variantasinteger" id="vai_r"/>
					<object type="variantasinteger" id="vai_g"/>
					<object type="variantasinteger" id="vai_b"/>
					<object type="modulo" id="mod_r"><property name="modulo">255</property></object>
					<object type="modulo" id="mod_g"><property name="modulo">255</property></object>
					<object type="modulo" id="mod_b"><property name="modulo">255</property></object>
				</objects>
				
				<connectors>
				
					<connector type="default">
						<output object="vai_r" name="value"/>
						<input object="mod_r" name="value"/>
					</connector>
					<connector type="default">
						<output object="mod_r" name="value"/>
						<input object="cc" name="red"/>
					</connector>
					
					<connector type="default">
						<output object="vai_g" name="value"/>
						<input object="mod_g" name="value"/>
					</connector>
					<connector type="default">
						<output object="mod_g" name="value"/>
						<input object="cc" name="green"/>
					</connector>
					
					<connector type="default">
						<output object="vai_b" name="value"/>
						<input object="mod_b" name="value"/>
					</connector>
					<connector type="default">
						<output object="mod_b" name="value"/>
						<input object="cc" name="blue"/>
					</connector>
					
				</connectors>
				<outputs>
					<output-export object="cc" name="color" export-name="color"/>
				</outputs>
				<inputs>
					<input-export object="vai_r" name="value" export-name="red"/>
					<input-export object="vai_g" name="value" export-name="green"/>
					<input-export object="vai_b" name="value" export-name="blue"/>
				</inputs>
			</template:template>
		</object-factory>
		
		<connector-factory id="default" class="org.openscada.da.client.viewer.model.impl.PassThroughConnectorFactory"/>
		<connector-factory id="display" class="org.openscada.da.client.viewer.model.impl.DisplaySynchronizedConnectorFactory"/>
